# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: sxds
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386

archive:
  format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
